import React from 'react';
import {
  BarChart3,
  BadgeDollarSign,
  BookOpen,
  Boxes,
  CircleHelp,
  Clock3,
  CreditCard,
  FileText,
  GitBranch,
  GitFork,
  Info,
  Home,
  KeyRound,
  Lock,
  Mail,
  Clipboard,
  Play,
  Plus,
  Search,
  ShieldCheck,
  Ticket,
  UserRound,
  WalletCards,
  Languages,
  LogIn,
  LogOut,
  Menu,
  MessageSquare,
  Network,
  Scale,
  Settings,
  Share2,
  Sparkles,
  Orbit,
  Layers3,
  ShoppingCart,
  Users,
  X,
} from 'lucide-react';

const icons = {
  home: Home,
  'bar chart': BarChart3,
  'balance scale': Scale,
  book: BookOpen,
  'clock outline': Clock3,
  'code branch': GitBranch,
  'credit card': CreditCard,
  cart: ShoppingCart,
  close: X,
  comments: MessageSquare,
  message: MessageSquare,
  sparkles: Sparkles,
  orbit: Orbit,
  layers: Layers3,
  dollar: BadgeDollarSign,
  github: GitFork,
  info: Info,
  envelope: Mail,
  'shield alternate': ShieldCheck,
  ticket: Ticket,
  wechat: MessageSquare,
  play: Play,
  plus: Plus,
  paste: Clipboard,
  search: Search,
  lock: Lock,
  'money bill alternate outline': WalletCards,
  key: KeyRound,
  language: Languages,
  login: LogIn,
  logout: LogOut,
  menu: Menu,
  network: Network,
  'question circle': CircleHelp,
  setting: Settings,
  share: Share2,
  'share alternate': Share2,
  sitemap: Boxes,
  user: UserRound,
  users: Users,
  file: FileText,
};

export function getIcon(name, props = {}) {
  const IconComponent = icons[name] || CircleHelp;
  return React.createElement(IconComponent, props);
}

export default icons;
